question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data_api = [
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "medium",
     "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "multiple",
     "difficulty": "hard",
     "question": "Who was not in the band &quot;The Smiths&quot;?",
     "correct_answer": "Martin Chambers",
     "incorrect_answers": ["Morrissey", "Andy Rourke", "Mike Joyce"]},
    {"category": "Entertainment: Film", "type": "multiple",
     "difficulty": "easy",
     "question": "Which actor plays Obi-Wan Kenobi in Star Wars Episodes I-lll?",
     "correct_answer": "Ewan McGregor",
     "incorrect_answers": ["Alec Guinness", "Hayden Christensen",
                           "Liam Neeson"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "In Super Mario Bros., who informs Mario that the princess is in another castle?",
     "correct_answer": "Toad",
     "incorrect_answers": ["Luigi", "Yoshi", "Bowser"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "&quot;The Potato Sack&quot; was a collection of indie games released on Steam in 2011 as a promotion for which game?",
     "correct_answer": "Portal 2",
     "incorrect_answers": ["Left 4 Dead 2", "Half-Life 3", "Dota 2"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "In &quot;Call Of Duty: Zombies&quot;, which map introduced the perk &quot;PhD Flopper&quot;?",
     "correct_answer": "Ascension",
     "incorrect_answers": ["Moon", "Call Of The Dead", "Die Rise"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple",
     "difficulty": "easy", "question": "How long is an IPv6 address?",
     "correct_answer": "128 bits",
     "incorrect_answers": ["32 bits", "64 bits", "128 bytes"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is Laos?", "correct_answer": "Country",
     "incorrect_answers": ["Region", "River", "City"]}
]
